version: '3.7'
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/go/src/github.com/peertransfer/terraform-provider-dkron
    command: tail -f /dev/null
    init: true

  dkron:
    image: dkron/dkron:v1.1.0
    ports:
      - 8081:8080
    command: agent --server   --log-level debug