version: '3.7'
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - ./:/go/src/github.com/peertransfer/terraform_plugin_dkron
    command: tail -f /dev/null

  deps:
    build:
      context: .
      target: deps
    volumes:
      - ./:/go/src/github.com/peertransfer/terraform_plugin_dkron

  dkron:
    image: dkron/dkron:v1.1.0
    ports:
      - 8081:8080
    command: agent --server   --log-level debug