version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"

    steps:
      - checkout

      - run:
          name: Build provider
          command: |
            VERSION=$(cat .semver)
            go build -mod=vendor -o ./terraform-provider-dkron_v$VERSION

      - run:
          name: Test provider
          command: |
            echo "Nothing to test yet..."

  release:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - run:
          name: Publish Release on GitHub
          command: |
            VERSION=$(cat .semver)
            go build -mod=vendor -o ./terraform-provider-dkron_v$VERSION
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./terraform-provider-dkron_v$VERSION

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
